const generesRouter = require("../router/genres");
const customerRouter = require("../router/customers");
const movieRouter = require("../router/movies");
const rentalRouter = require("../router/rentals");
const userRouter = require("../router/users");
const authRouter = require("../router/auth");
const homeRouter = require("../router/home");
const error = require("../middleware/error");
const express = require('express');
module.exports = (app) => {
  app.use(express.json());
  app.use("/", homeRouter);
  app.use("/api/genres", generesRouter);
  app.use("/api/customers", customerRouter);
  app.use("/api/movies", movieRouter);
  app.use("/api/rentals", rentalRouter);
  app.use("/api/users", userRouter);
  app.use("/api/auth", authRouter);
  app.use(error);
};